### ISSUE TITLE
Can't include an interceptor in ngProviders section in GridConfigGenerator

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular-samples#388]
### Description  
When Interceptor is added to a sample ngProviders section in the GridConfigGenerator, 

```
ngProviders: [
                    RemoteService,
                    RequestCachingService,
                    {
                        provide: HTTP_INTERCEPTORS,
                        useClass: CachingInterceptor,
                        multi: true
                    }
                ]
```

build throws an error.

### Result  
```
[15:29:12] TypeError: Cannot read property 'trim' of undefined
    at SampleAssetsGenerator._formatAppModuleTypes (D:\Work\igniteui-angular-samples\live-editing\generators\SampleAssetsGenerator.ts:327:63)
    at SampleAssetsGenerator._getAppModuleConfig (D:\Work\igniteui-angular-samples\live-editing\generators\SampleAssetsGenerator.ts:238:32)
    at SampleAssetsGenerator._generateSampleAssets (D:\Work\igniteui-angular-samples\live-editing\generators\SampleAssetsGenerator.ts:125:60)
```

**Comment by sboykova** [comment]
Won't be needed for now, closing the issue.
