### ISSUE TITLE
Sample browser is throwing errors when loading the main page

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-angular-samples#916]
### Steps to reproduce  

- pull latest changes on master branch
- run "npm install"
- run "npm start"
- open http://localhost:4200/
- observer logs in debug console

### Expected Result  
the main page loads without errors

### Actual Result  
the main page loads with errors and users cannot navigate to any sample

client:168 : TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:16637:21)
    at Object.isEffectiveExternalModule (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:8680:19)
    at checkExternalEmitHelpers (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:57702:24)
    at checkDecorators (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:53268:13)
    at checkClassLikeDeclaration (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:54988:13)
    at checkClassDeclaration (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:54982:13)
    at checkSourceElement (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:56153:28)
    at Object.forEach (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:210:30)
    at checkSourceFileWorker (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:56317:20)
    at checkSourceFile (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:56289:13)
    at Object.forEach (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:210:30)
    at getDiagnosticsWorker (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:56382:16)
    at getDiagnostics (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:56350:24)
    at Object.getEmitResolver (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:31393:13)
    at emitWorker (C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:86924:69)
    at C:\REPOS\IgniteUI\igniteui-angular-samples\node_modules\typescript\lib\typescript.js:86887:66

**Comment by HristoP96** [comment]
This behavior most likely is caused because of the **npm start** scripts order. I will make a PR with fixed run scripts order on the "start" script in package.json, this may resolve the problem.
